import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import { ConfigProvider } from 'antd';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '花狮心途',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="ch">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased text-blackFist text-[16px]`}>
      <AntdRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#C3E006',
            },
          }}>
          <div className="h-screen w-full overflow-hidden">
            <div className="relative mx-auto h-full w-full max-w-screen-sm bg-[#F5F5F5]">
              {/* 内容 */}
              <div
                style={{
                  background:
                    'linear-gradient(180deg, #EAF994 0%, rgba(255, 255, 255, 0) 60%)',
                }}
                className="absolute top-0 left-0 h-full w-full z-20 overflow-x-hidden overflow-y-auto pb-3">
                {children}
              </div>
            </div>
          </div>
        </ConfigProvider>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
